[2022-09-10 15:27:17,854][__main__][INFO] - device: cuda:0
[2022-09-10 15:27:17,854][deepke.relation_extraction.standard.utils.ioUtils][INFO] - load data from /home/zzx/deepke/DeepKE/example/re/standard/data/out/vocab.pkl
Traceback (most recent call last):
  File "run.py", line 61, in main
    vocab = load_pkl(vocab_path)
  File "/home/zzx/deepke/DeepKE/src/deepke/relation_extraction/standard/utils/ioUtils.py", line 36, in load_pkl
    with open(fp, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zzx/deepke/DeepKE/example/re/standard/data/out/vocab.pkl'
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.